version: '3.8'

services:
  mysql-master:
    image: mysql:8.0.33
    build:
      context: ../services/mysql
      dockerfile: ./Dockerfile
    hostname: mysql_master
    container_name: mysql_master
    networks:
      dev_net:
        ipv4_address: ${MYSQL_IP}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PW}
      MYSQL_DATABASE: default_db
      TZ: Asia/Seoul
    volumes:
      - ../init/mysql_master/my.cnf:/etc/mysql/my.cnf
      - ../init/mysql_master:/docker-entrypoint-initdb.d
      - mysql_data_master:/var/lib/mysql:rw
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
  mysql-slave:
    image: mysql:8.0.33
    build:
      context: ../services/mysql
      dockerfile: ./Dockerfile
    hostname: mysql_slave
    container_name: mysql_slave
    networks:
      dev_net:
        ipv4_address: ${MYSQL_SLAVE_IP}
    ports:
      - ${MYSQL_SLAVE_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SLAVE_ROOT_PW}
      MYSQL_DATABASE: default_db
      TZ: Asia/Seoul
    volumes:
      - ../init/mysql_slave/my.cnf:/etc/mysql/my.cnf
      - ../init/mysql_slave:/docker-entrypoint-initdb.d
      - mysql_data_slave:/var/lib/mysql:rw
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql-master:
        condition: service_healthy
  redis:
    image: redis:7.0.11
    build:
      context: ../services/redis
      dockerfile: ./Dockerfile
    hostname: redis
    container_name: redis
    restart: always
    networks:
      dev_net:
        ipv4_address: ${REDIS_IP}
    ports:
      - ${REDIS_PORT}:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    volumes:
      - redis_data:/data:rw
      - redis_conf:/usr/local/conf:rw
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
  memcached:
    image: memcached:1.6.18
    build:
      context: ../services/memcached
      dockerfile: ./Dockerfile
    hostname: memcached
    container_name: memcached
    restart: always
    networks:
      dev_net:
        ipv4_address: ${MEMCACHED_IP}
    ports:
      - ${MEMCACHED_PORT}:11211
    command: [ "-m", "1024" ]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    depends_on:
      mysql-slave:
        condition: service_healthy